### ISSUE TITLE
[Importer] CSV import broken in cli image (does not adhere to the v3 schema)

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#10923]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I just noticed today my daily import fails to parse my CSV files. I have 2 types of account imports:
- GoCardLess which is working fine
- CSV export from some banks for which GoCardLess is not available (like saving accounts etc...)

Lucky for me I noticed I should have transactions that I did not had because the importer just fails with error code 69 for these but I don't get any email alert.
I'm using the develop image on docker running on a Synology (managed with Portainer):
- fireflyiii/data-importer:develop : sha256:9d650e291911d1832ef08e116c858334055d8a6319d20176a44e10c24c88e9ee
- fireflyiii/data-importer:develop-cli : sha256:893c7b7ef8aae6a39577395855c54159af1b402785532ccb025def70c568b77a

I give both the regular UI and the CLI images because they just end up with a different behavior.
My issue is when running the cli version and providing the same json and csv, I get this error
```
[2025-09-17 07:58:07] production.ERROR: Configuration file "/import/MyFile.json" does not adhere to the v3 schema: Array expected,
```
Then it shows my complete mapping list from the json on one line ending with
```
received at #->properties:mapping
```
and after that
```
[2025-09-17 07:58:07] production.ERROR: [develop/2025-09-16] Exit code is CANNOT_PARSE_CONFIG.  
[2025-09-17 07:58:07] production.DEBUG: Collection of exit codes: 69  
```

So this is only in the cli version. When I use the regular develop and provide the same json and csv, the import works fine.

BTW thanks a lot for the name of the imported file in the email report. So cool to finally know which account imported which transactions!!!
And again thank you so much for this amazing tool!

### Debug information

Relevant output has been provided above

### Steps to reproduce

Use the regular develop image where it works, then use same json/csv in the cli version it fails

**Comment by JC5** [comment]
Glad to hear you like it!

But nice find, this is on `develop` indeed. I am experimenting with config file validation. Mine works, but you know: there are more import formats out there.

I've committed a fix and created new `develop(-cli)` image. I'm hoping this will work, I haven't got the resources right now to test this. If it doesn't work I will pick it up later and test thoroughly myself. Thanks in advance for checking it out!

**Comment by MacPaille** [comment]
No worries I moved to develop images because most of the fixes I needed when reporting a but were deployed there and I never swapped back to latest :-) And I'm not finger pointing that's normal from a develop image to have issues.

I was just happy to report the bug as the behavior between the cli and regular version is different.

I just tested with the latest develop-cli and issue is still the same, even if now it seems the json can't be parsed at all
```
The importer can't import /import/MyFile.csv: could not decode the JSON in config file /import/MyFile.json.
```
Didn't changed a thing in the json or the CSV. Anyway does not impact me that much as I can use the UI version to import my transactions. Just take a bit more time but it's ok until fixed

**Comment by MacPaille** [comment]
Anyway I just swapped back to latest-cli and it's working fine there

**Comment by JC5** [comment]
> Didn't changed a thing in the json or the CSV. Anyway does not impact me that much as I can use the UI version to import my transactions. Just take a bit more time but it's ok until fixed

Sorry, I wasn't able to replicate this and the schema is also valid JSON. All I was able to find is that the export function outputs `mapping: []`, but the new scheme requires `mapping: {}`.

**Comment by JC5** [comment]
A note: it will also accept `[]`

**Comment by MacPaille** [comment]
I do already use mapping: {} but then it has the field that the map is for like
```
"mapping": {
  "2": {
    XXXXXX
  }
},
```
Do you have a json template I can check my own file against? Normally I'm just trying to use the UI importer, download the resulting file and merging anything that is not in my original file...
So the only difference is the mapping part

**Comment by JC5** [comment]
Yes, it is stored here: https://github.com/firefly-iii/data-importer/blob/develop/resources/schemas/v3.json
