### ISSUE TITLE
Walkthrough Popup shows up every time

### ISSUE THREAD

**Issue by newhinton** [firefly-iii/firefly-iii#1147]
I am running Firefly III version 4.6.3.1

#### Description of my issue:
The walkthrough popup shows up every time the page is loaded
#### Steps to reproduce 
Reload page

The problem does not exist on the demo page

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
Hi! This bug is fixed later versions. I suggest you upgrade. Don’t forget to make a backup!

**Comment by newhinton** [comment]
Thanks for your response!

I will do that, but there seems a small problem:
The command:
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated <next_version>

where <next_version>  was replaced with 4.7.2;4.7.1;4.7.0;
does not find any version. 

only leaving out the version number results in the version 4.6.1 beeing installed. Do you have any adivce regarding this problem? what is my mistake here?

**Comment by JC5** [comment]
Are you running php 7.0 by any chance? Because later versions require php 7.1.

**Comment by newhinton** [comment]
Yes i was running 7.0, i have now 7.1 installed
Apache still uses 7.0, because i didn't finish the proper config to use 7.1 specifically on that vhost, but the cli uses 7.1, as $php -v reveals. But the command still does not work.
Does composer rely on apache using php7.1?

**Comment by JC5** [comment]
The latest version is 4.6.13, does that work?

**Comment by newhinton** [comment]
Yes, that worked. I have mistaken the Roadmap for the version list. Should have paid more attention.
But thank you for your help nonetheless!

Now i have to figure out how to get apache to use 7.0 and 7.1 alongside
