### ISSUE TITLE
Show only certain accounts for withdrawal transaction

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2534]
I would like Firefly III to show only certain account when do **new withdrawal transaction**.
![image](https://user-images.githubusercontent.com/25054050/64159387-d8aeab80-ce42-11e9-8cd6-b9e27ef7c72a.png)

I do withdrawal only from few credit cards and from cash, but in **Source account** I have everything: all bank accounts, all revenue accounts.

Instead of having only 4 option, I see 10, it is to much and confusing.

It is better to have option to show in **Source account**  only account I chose.

It will be more clear and nice for the user to make a withdrawal.

**Comment by JC5** [comment]
This is by design, the form is the same for every view. Just start typing and the account you'll need will be selected.

**Comment by jlauwers** [comment]
From the docs;
> For example, if you shop at the place you work at, you will have a revenue account called “Albert Heijn” from which your salary is drawn but also an expense account called “Albert Heijn” where you pay your groceries.

From what I understand, you should only be able to put a revenue or asset account in source account.
And only be able to put a expense or asset account in destination account.

If I have a bakery expense account, should it be available in source account?
Right now it is available.

**Comment by JC5** [comment]
Like I said, the form is the same for every type of transaction. This adds flexibility. The system will automatically pick the correct account based on the input in both fields.

**Comment by jlauwers** [comment]
Right now, I could put in __source__ account, Bakery (__expense account__, available in dropdownlist) and in destination my bank account.

That creates a new __revenue__ account Bakery and creates the transaction.
So I don't really see why it was available in the first place since it created a new account anyway.

**Comment by JC5** [comment]
You have a good point there 😅  I think that would be an easy fix, that makes sense as well. Thanks for the feedback 👍

**Comment by JC5** [comment]
Pushed something :+1:

**Comment by optimistic5** [comment]
Thank you for your anser.
I will explain my point one more time.

I have some sources of income. Lets say this is my salary, salary of my wife, I collect coins from fountain and some other sources.
In total I have **6 Revenue accounts**. 
I will newer spend money from this account, I will transfer money from revenue accounts to another accounts.

I have some savings account. 
Lets say I have tree saving account in tree currency, the same for my wife and dog :)
In total **9 saving account**. 
This accounts I will use only for saving money, I will not spend (withdraw) money from them.

I have some account from which I made my purchases. I use it for withdrawing money.
Lets say I have cash, two credit card, few credit card of my wife.
In total I have **5 accounts** from which I will **withdraw** money.
**And I will withdraw money only from this account.**

So, right now when I made withdraw I see **all 20 accounts**, but I need to choose only from **5**.
I hope you understand my point.
Thank you :)

**Comment by JC5** [comment]
Yes, and this is fixed in the next release :)

**Comment by jlauwers** [comment]
> Pushed something 👍

I don't see it in develop yet :(

**Comment by JC5** [comment]
Forgot to push, here you go!

**Comment by jlauwers** [comment]
Sadly, I still see expense account in source account field and revenue account in destination account field.

![image](https://user-images.githubusercontent.com/1318140/64427498-a5258880-d0b1-11e9-9fbb-a96b74bfa361.png)

**Comment by JC5** [comment]
That could be your browser caching things but I’ll check it later.

**Comment by jlauwers** [comment]
I created brand new accounts so I don't think caching is involved.

**Comment by JC5** [comment]
It wasn't, nope. Could you try this?

**Comment by jlauwers** [comment]
It's working 😁
