### ISSUE TITLE
unable to post a transaction

### ISSUE THREAD

**Issue by 4e868df3** [firefly-iii/firefly-iii#3080]
**Bug description**
I am running Firefly III version 5.0.1. I am on Debian 10 and am using php 7.3. When I post a transaction to /api/v1/transactions, I get a 500 error. Same issue with 5.0.4. I was hoping someone could tell me if I am getting all of the right required fields below, and if you have any tips for debugging which field might be the culprit. Thank you!

```
...
data = {
    'transactions': [
        {
        'date': '2020-01-29', 
        'amount': 6.33, 
        'description': '', 
        'category_name': 'Travel', 
        'source_id': 12, 
        'destination_name': 'Uber', 
        'type': 'withdrawal'
        }
    ]
}
res = requests.post(firefly_url + "/api/v1/transactions", data=data, headers={'Authorization': 'Bearer '+firefly_personal_access_token})
<Response [500]>
```

```
tail /var/www/firefly-iii/storage/logs/ff3-fpm-fcgi-2020-02-03.log
[2020-02-03 16:18:45] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"count(): Parameter must be an array or an object that implements Countable","time":"Mon, 03 Feb 2020 16:18:45 -0700","file":"\/var\/www\/firefly-iii\/app\/Validation\/TransactionValidation.php","line":247,"code":0,"version":"5.0.1","url":"https:\/\/firefly.***.com\/api\/v1\/transactions","userAgent":"python-requests\/2.22.0","json":true}  
[2020-02-03 16:18:45] local.ERROR: count(): Parameter must be an array or an object that implements Countable {"userId":1,"exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /var/www/firefly-iii/app/Validation/TransactionValidation.php:247)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/firefl...', 247, Array)
#1 /var/www/firefly-iii/app/Validation/TransactionValidation.php(247): count('type')
#2 /var/www/firefly-iii/app/Api/V1/Requests/TransactionStoreRequest.php(170): FireflyIII\\Api\\V1\\Requests\\TransactionStoreRequest->validateOneTransaction(Object(FireflyIII\\Validation\\FireflyValidator))
#3 [internal function]: FireflyIII\\Api\\V1\\Requests\\TransactionStoreRequest->FireflyIII\\Api\\V1\\Requests\\{closure}(Object(FireflyIII\\Validation\\FireflyValidator))
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(268): call_user_func_array(Object(Closure), Array)
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(316): Illuminate\\Validation\\Validator->Illuminate\\Validation\\{closure}()
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(329): Illuminate\\Validation\\Validator->passes()
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(25): Illuminate\\Validation\\Validator->fails()
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()
...
```

- [x] Nobody reported this bug before
- [x] I have added a stack trace from my log files.
- N/A: I have added a screenshot.
- N/A I was able to replicate it on the demo site https://demo.firefly-iii.org/ (demo site is broken)

**Comment by JC5** [comment]
It seems to be a bug, I'll check it out.

**Comment by JC5** [comment]
Just as an FYI, the JSON you've posted here as an example is bad. You're missing your closing `}` and the description is badly escaped: `'description': '', ` should be `'description': \'', `

Nevertheless, Firefly III should be able to handle that. I've pushed a fix for the next release.

**Comment by mh00h** [comment]
> Just as an FYI, the JSON you've posted here as an example is bad. You're missing your closing `}`. Nevertheless, Firefly III should be able to handle that. I've pushed a fix for the next release.
> 
> Edit: I was wrong about the description being badly formatted as well.

Good catch, I've updated my comment. I wasn't sure if description is required or not after looking at swagger, hence why it is there.

**Comment by 4e868df3** [comment]
Good catch, I updated the original post.

After copying your changes into my server, I still have an error.

```
#0 /var/www/firefly-iii/app/Validation/TransactionValidation.php(148): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Invalid argumen...', '/var/www/firefl...', 148, Array)
#1 /var/www/firefly-iii/app/Api/V1/Requests/TransactionStoreRequest.php(173): FireflyIII\Api\V1\Requests\TransactionStoreRequest->validateDescriptions(Object(FireflyIII\Validation\FireflyValidator))
#2 [internal function]: FireflyIII\Api\V1\Requests\TransactionStoreRequest->FireflyIII\Api\V1\Requests\{closure}(Object(FireflyIII\Validation\FireflyValidator))
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(270): call_user_func_array(Object(Closure), Array)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(318): Illuminate\Validation\Validator->Illuminate\Validation\{closure}()
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(331): Illuminate\Validation\Validator->passes()
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(25): Illuminate\Validation\Validator->fails()
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\Foundation\Http\FormRequest->validateResolved()
...
```

**Comment by JC5** [comment]
Weird. I’ll add some debug code.

**Comment by 4e868df3** [comment]
This is resolved after following one more suggestion of JC5. Closing this ticket.

> Make sure you add "Accept: application/json" to your request. Maybe something else will pop up then.
