### ISSUE TITLE
DEVELOP: TransactionMatcher not found

### ISSUE THREAD

**Issue by verticelo** [firefly-iii/firefly-iii#3735]
**Bug description**
I am running Firefly III version develop (https://hub.docker.com/layers/jc5x/firefly-iii/develop/images/sha256-a84d7949cff55e208a158c3cac4c89f643f95084b2df906398c6a50bc881edab?context=explore), and my problem is:

- I have created a rule
- When I press to test the rule, an error is displayed "Cannot get transactions for given triggers"
- When I press to run the rule, it does not match any transactions

**Steps to reproduce**
- Create a rule, then try to run it

**Extra info**
```
2020-08-26T15:30:07.079092350Z [2020-08-26 15:30:07] local.ERROR: Target class [FireflyIII\TransactionRules\TransactionMatcher] does not exist. {"userId":1,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [FireflyIII\\TransactionRules\\TransactionMatcher] does not exist. at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:811)


2020-08-26T15:30:07.079116138Z [stacktrace]


2020-08-26T15:30:07.079121429Z #0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()


2020-08-26T15:30:07.079126350Z #1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()


2020-08-26T15:30:07.079130593Z #2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()


2020-08-26T15:30:07.079134859Z #3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()


2020-08-26T15:30:07.079146872Z #4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make()


2020-08-26T15:30:07.079151494Z #5 /var/www/firefly-iii/app/Http/Controllers/Rule/SelectController.php(223): app()


2020-08-26T15:30:07.079155341Z #6 [internal function]: FireflyIII\\Http\\Controllers\\Rule\\SelectController->testTriggersByRule()


2020-08-26T15:30:07.079159628Z #7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()


2020-08-26T15:30:07.079163566Z #8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()


2020-08-26T15:30:07.079167751Z #9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()


2020-08-26T15:30:07.079171817Z #10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()


2020-08-26T15:30:07.079175886Z #11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()


2020-08-26T15:30:07.079180738Z #12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()


2020-08-26T15:30:07.079185045Z #13 /var/www/firefly-iii/app/Http/Controllers/Rule/SelectController.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079189211Z #14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Controllers\\Rule\\SelectController->FireflyIII\\Http\\Controllers\\Rule\\{closure}()


2020-08-26T15:30:07.079193672Z #15 /var/www/firefly-iii/app/Http/Controllers/Controller.php(108): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079197719Z #16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}()


2020-08-26T15:30:07.079201960Z #17 /var/www/firefly-iii/app/Http/Middleware/InterestingMessage.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079206042Z #18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InterestingMessage->handle()


2020-08-26T15:30:07.079210132Z #19 /var/www/firefly-iii/app/Http/Middleware/Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079214136Z #20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()


2020-08-26T15:30:07.079218160Z #21 /var/www/firefly-iii/app/Http/Middleware/Range.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079222174Z #22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Range->handle()


2020-08-26T15:30:07.079229716Z #23 /var/www/firefly-iii/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079234169Z #24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): PragmaRX\\Google2FALaravel\\Middleware->handle()


2020-08-26T15:30:07.079238332Z #25 /var/www/firefly-iii/app/Http/Middleware/Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079242767Z #26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()


2020-08-26T15:30:07.079246908Z #27 /var/www/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079251044Z #28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()


2020-08-26T15:30:07.079255200Z #29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079259456Z #30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()


2020-08-26T15:30:07.079263465Z #31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079267555Z #32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()


2020-08-26T15:30:07.079271691Z #33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079275773Z #34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()


2020-08-26T15:30:07.079279822Z #35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079284036Z #36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()


2020-08-26T15:30:07.079288251Z #37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()


2020-08-26T15:30:07.079292728Z #38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079297054Z #39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()


2020-08-26T15:30:07.079304580Z #40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079309107Z #41 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()


2020-08-26T15:30:07.079313258Z #42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079317376Z #43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()


2020-08-26T15:30:07.079321286Z #44 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()


2020-08-26T15:30:07.079325315Z #45 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()


2020-08-26T15:30:07.079329260Z #46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()


2020-08-26T15:30:07.079333299Z #47 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()


2020-08-26T15:30:07.079337362Z #48 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()


2020-08-26T15:30:07.079341642Z #49 /var/www/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079345635Z #50 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()


2020-08-26T15:30:07.079349621Z #51 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079354039Z #52 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()


2020-08-26T15:30:07.079358082Z #53 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079362273Z #54 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()


2020-08-26T15:30:07.079366337Z #55 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079370448Z #56 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()


2020-08-26T15:30:07.079374446Z #57 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079381540Z #58 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()


2020-08-26T15:30:07.079386009Z #59 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079390412Z #60 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()


2020-08-26T15:30:07.079394639Z #61 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079398686Z #62 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()


2020-08-26T15:30:07.079402653Z #63 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079406662Z #64 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()


2020-08-26T15:30:07.079410881Z #65 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()


2020-08-26T15:30:07.079415044Z #66 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()


2020-08-26T15:30:07.079418896Z #67 {main}


2020-08-26T15:30:07.079422265Z 


2020-08-26T15:30:07.079425677Z [previous exception] [object] (ReflectionException(code: -1): Class FireflyIII\\TransactionRules\\TransactionMatcher does not exist at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:809)


2020-08-26T15:30:07.079429930Z [stacktrace]


2020-08-26T15:30:07.079433320Z #0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(809): ReflectionClass->__construct()


2020-08-26T15:30:07.079437175Z #1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()


2020-08-26T15:30:07.079441168Z #2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()


2020-08-26T15:30:07.079445141Z #3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()


2020-08-26T15:30:07.079449161Z #4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()


2020-08-26T15:30:07.079453164Z #5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make()


2020-08-26T15:30:07.079460312Z #6 /var/www/firefly-iii/app/Http/Controllers/Rule/SelectController.php(223): app()


2020-08-26T15:30:07.079464355Z #7 [internal function]: FireflyIII\\Http\\Controllers\\Rule\\SelectController->testTriggersByRule()


2020-08-26T15:30:07.079468295Z #8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()


2020-08-26T15:30:07.079472080Z #9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()


2020-08-26T15:30:07.079476111Z #10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()


2020-08-26T15:30:07.079480108Z #11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()


2020-08-26T15:30:07.079484351Z #12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()


2020-08-26T15:30:07.079488303Z #13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()


2020-08-26T15:30:07.079492350Z #14 /var/www/firefly-iii/app/Http/Controllers/Rule/SelectController.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079496338Z #15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Controllers\\Rule\\SelectController->FireflyIII\\Http\\Controllers\\Rule\\{closure}()


2020-08-26T15:30:07.079500608Z #16 /var/www/firefly-iii/app/Http/Controllers/Controller.php(108): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079504525Z #17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}()


2020-08-26T15:30:07.079508765Z #18 /var/www/firefly-iii/app/Http/Middleware/InterestingMessage.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079512715Z #19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InterestingMessage->handle()


2020-08-26T15:30:07.079516767Z #20 /var/www/firefly-iii/app/Http/Middleware/Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079520766Z #21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()


2020-08-26T15:30:07.079524736Z #22 /var/www/firefly-iii/app/Http/Middleware/Range.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079528690Z #23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Range->handle()


2020-08-26T15:30:07.079532781Z #24 /var/www/firefly-iii/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079539731Z #25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): PragmaRX\\Google2FALaravel\\Middleware->handle()


2020-08-26T15:30:07.079544521Z #26 /var/www/firefly-iii/app/Http/Middleware/Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079548653Z #27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()


2020-08-26T15:30:07.079552700Z #28 /var/www/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079556759Z #29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()


2020-08-26T15:30:07.079560869Z #30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079564958Z #31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()


2020-08-26T15:30:07.079569061Z #32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079573146Z #33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()


2020-08-26T15:30:07.079577182Z #34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079581260Z #35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()


2020-08-26T15:30:07.079585266Z #36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079589290Z #37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()


2020-08-26T15:30:07.079593672Z #38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()


2020-08-26T15:30:07.079597783Z #39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079601905Z #40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()


2020-08-26T15:30:07.079605984Z #41 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079613058Z #42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()


2020-08-26T15:30:07.079617383Z #43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079621473Z #44 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()


2020-08-26T15:30:07.079625486Z #45 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()


2020-08-26T15:30:07.079629525Z #46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()


2020-08-26T15:30:07.079633424Z #47 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()


2020-08-26T15:30:07.079637421Z #48 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()


2020-08-26T15:30:07.079641301Z #49 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()


2020-08-26T15:30:07.079645521Z #50 /var/www/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079665337Z #51 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()


2020-08-26T15:30:07.079671973Z #52 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079676269Z #53 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()


2020-08-26T15:30:07.079680151Z #54 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079684246Z #55 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()


2020-08-26T15:30:07.079688427Z #56 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079692502Z #57 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()


2020-08-26T15:30:07.079696537Z #58 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079704607Z #59 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()


2020-08-26T15:30:07.079709056Z #60 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079713246Z #61 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()


2020-08-26T15:30:07.079717342Z #62 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079721308Z #63 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()


2020-08-26T15:30:07.079725228Z #64 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()


2020-08-26T15:30:07.079730045Z #65 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()


2020-08-26T15:30:07.079734010Z #66 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()


2020-08-26T15:30:07.079738045Z #67 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()


2020-08-26T15:30:07.079741865Z #68 {main}


2020-08-26T15:30:07.079745221Z "} 


2020-08-26T15:30:07.081697682Z 192.168.0.10 - - [26/Aug/2020:15:30:07 +0000] "GET /rules/test-rule/7 HTTP/1.1" 500 3045 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
```

**Comment by JC5** [comment]
Yes that's why it's a develop version.

**Comment by verticelo** [comment]
Yes, I logged it so you can be aware of it prior to an alpha promotion etc.. If you do not care about bugs in the develop version please let me know and I won't file any additional. Have found three more bugs.

**Comment by JC5** [comment]
Haha no worries, apart from the bug you said nothing else so I wasn't sure what you wanted to tell me. Would you believe some people got very angry with me for breaking the develop branch? I was afraid it would be something like that.

Which other bugs did you find? I'm happy to hear about it!

**Comment by JC5** [comment]
Found and fixed :+1:

**Comment by verticelo** [comment]
Thanks, but something else broke now. Whenever I click "Edit" on a rule, the list of triggers doesn't map correctly, ie. the trigger dropdown is completely blank/empty but the value is set.

Also, when I try to run the rule it doesn't work, it doesn't change the transactions.

**Comment by JC5** [comment]
Thanks, I'll verify. The rule engine is getting a complete make-over. I think I know what's happening in this particular case.

**Comment by JC5** [comment]
I pushed some changes. I can't really tell why your rules don't fire but check out the beaker icon on `/rules` to see what the results are. Then verify if/why it doesn't apply the actions using the log files if necessary.

**Comment by verticelo** [comment]
Unfortunately it doesn't seem to be working still. Please see the screenshot below of how it looks when I try to create a rule from an existing expense transaction.

![image](https://user-images.githubusercontent.com/360131/91494756-a1d66e80-e8b9-11ea-8821-75daf305b6fb.png)

**Comment by JC5** [comment]
Also sneaked in some changes to fix that!

**Comment by verticelo** [comment]
Some progress now! The Trigger names now show. However, the rule still won't run on the transaction and doesn't affect them. I can do the test and find/see the transactions that would apply on them but it never changes the category on them so something is still broken.

Rule spec:

![image](https://user-images.githubusercontent.com/360131/91536910-c102e980-e915-11ea-9bcd-101f58eee466.png)

**Comment by JC5** [comment]
That one was tricky. But it works for me ™️  now. I pushed a new develop image, could you verify?

**Comment by verticelo** [comment]
Working now! Good job!
