### ISSUE TITLE
ynab-importer GuzzleException: cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by sec12tst8r84** [firefly-iii/firefly-iii#4286]
Hello, I've just started using firefly and tried to install the ynab-importer.  Both are running off of WAMP on Windows 10.  In the ynab env file, I have put the YNAB Personal Access Token as well as the Firefly Access Token.  What may I be doing wrong?

As a FYI, when I first set up the importer, the start button as well as other css elements were missing.  The fix was to setup a virtual host so ynab is at / rather than ynab-importer/public.  The csv importer did not have this requirement.  With the way the documentation is written, I had assumed virtual hosts were optional.
![Screenshot 2021-01-18 103222](https://user-images.githubusercontent.com/5523999/104934745-793e3680-5978-11eb-8462-5117f0123e1c.png)

**Comment by JC5** [comment]
Googling the error seems to return pretty straight forward solutions. Have you tried those?

**Comment by sec12tst8r84** [comment]
Thank you for responding so quickly. Unsure why my initial google yielded no results.  I managed to get past this error.  A second one came up saying the login for the database was incorrect so I had to update that in the ynab env file.  I did not set it at first as the env file stated that the tool uses no DB.

I now have a new issue where it says Class 'App\Http\Request\Carbon' not found.  It seems like I may need to add the line: 

'Carbon' => 'Carbon\Carbon',

but do you know where I need to add this?

**Comment by JC5** [comment]
I don't think you need to do that. Neither does the YNAB use a database. I'm not really sure why it complains about that.

Having said that, do you have a stack trace for the error you're getting?

**Comment by JC5** [comment]
Never mind, looks like you found a bug. I'll try to fix it over the weekend.

**Comment by sec12tst8r84** [comment]
FYI, this was the error I got if I did not update the DB information.  Thank you for all your hard work

![Screenshot 2021-01-19 083041](https://user-images.githubusercontent.com/5523999/105041217-b5cd6900-5a30-11eb-989b-17a79bd58569.png)

**Comment by JC5** [comment]
That is an error sent by Firefly III itself.

**Comment by JC5** [comment]
I pushed some fixes to the "develop" branch + docker image. Would appreciate it if you could give it a try.

**Comment by sec12tst8r84** [comment]
Apologies, how do I setup the develop branch of ynab importer if I am self-hosting with WAMP?

**Comment by JC5** [comment]
Good question, sorry for not pointing it out!

Either you download [develop.zip](https://github.com/firefly-iii/ynab-importer/archive/develop.zip) or grab version `dev-main` instead of the latest version (when using composer)

**Comment by sec12tst8r84** [comment]
Okay, I unzipped develop and it seems like a version of firefly rather than ynab importer.  I changed the env in ynab importer to point to this version of firefly.  Unfortunately, the Carbon error is still there.

**Comment by JC5** [comment]
What? It's the YNAB importer.

**Comment by sec12tst8r84** [comment]
That was my mistake.  I copied the env from the original ynab importer over to this develop one.  I now see this error:

![image](https://user-images.githubusercontent.com/5523999/105075915-63a03e00-5a58-11eb-875b-0d43b532edbc.png)

**Comment by sec12tst8r84** [comment]
I copied the vendor folder over from the original to this develop one.  As a test, I chose a date range to import.  This is the error I get.

![image](https://user-images.githubusercontent.com/5523999/105076538-2c7e5c80-5a59-11eb-9940-337748aced3c.png)

**Comment by JC5** [comment]
Thanks. I'm afraid the two of us have some debugging to do. YNAB won't let me access the API without a paid account so i can't check if things work (they have no sandbox).

As you run into errors I'll debug and update the develop.zip link above. Just re-download and apply it.

How did you install it last time?

**Comment by sec12tst8r84** [comment]
I will send you my login for ynab.  It's a test account on a trial subscription with minimal transactions as I wanted to make sure everything works before I import everything on there.  I unzipped the file onto my Websites folder and added an entry in virtual hosts.  I copied over the env file from the orig ynab and then later copied the vendor folder.  Then, I went to http://ynab-develop (the url for the virtual host).

**Comment by JC5** [comment]
I saw that, thank you. I'll use it to patch up the YNAB importer over the next few days. Thanks for the trust!

**Comment by sec12tst8r84** [comment]
Thank you for all your hard work.  I can't wait to use firefly to keep my finances in check!  Feel free to create whatever you need in the ynab account.

**Comment by JC5** [comment]
I pushed a new version and some quick checks make me believe it works now. Thanks again!

**Comment by sec12tst8r84** [comment]
Oh wow. Thank you for working so quickly. My test shows that everything is working great.  Have a great weekend!
