### ISSUE TITLE
5.6.0 v2: UI broken due to date formatting issues

### ISSUE THREAD

**Issue by niklas2810** [firefly-iii/firefly-iii#5100]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi there,

all transaction lists are broken on my Firefly III installation (5.6.0 on Docker, using v2 layout).

Please see the attached screenshot, it seems like some template is not filled properly due to an error (see console log, my PC locale is set to german, where a different time and date format is used; might that be the root cause?).

If you need more details, please let me know and I'll be happy to provide them to you. Btw.: The transactions list on the dashboard works just fine.

### Expected behaviour

Transaction lists should be displayed properly

### Debug information

Debug information generated at 2021-09-19 19:13:52 Europe/Berlin for Firefly III version **5.6.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.0 |
| Firefly III API | 1.5.3 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 17ce7331-7b74-4692-87c3-58a81f1b8064 |
| Using docker? | true |
| Telemetry | false |
| Layout | v2 |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2020-05-15 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.47 |

### Steps to reproduce

1. Install version 5.6.0 via docker, use v2 layout.
2. Set your PC/browser locale to a non-standard english locale (here: German).
3. Most transactions lists are now broken (i tested `/transactions/<type>` and `/accounts/<id>`)

I didn't see the error anywhere else.

### Additional info

![image](https://user-images.githubusercontent.com/30748216/133936726-1d802acc-c017-4e8c-a75f-dc2205443cf8.png)

**Comment by niklas2810** [comment]
Account overview looks quite similar: 
![image](https://user-images.githubusercontent.com/30748216/133936768-685385f3-386f-483a-b926-e78925793699.png)

**Comment by niklas2810** [comment]
I use Firefly III behind traefik, but I don't think that's relevant here.

**Comment by niklas2810** [comment]
Tested this a bit, and it doesn't seem to be limited to transactions only. Here's a screenshot from `/subscriptions`: ![image](https://user-images.githubusercontent.com/30748216/133936875-9694af1e-2d48-40ae-929b-99e2380d0bd0.png)

**Comment by niklas2810** [comment]
Might be relevant as well: On `/transactions/transfers`, I think there is a cache error: 
![image](https://user-images.githubusercontent.com/30748216/133936919-e2e6a441-2926-401a-ae54-b13958b3a761.png)

Might this be the same issue as in #5092 ? I hope the screenshots will help you to find the issue, if you need more info just let me know 👍

**Comment by JC5** [comment]
This is something else. Looking at the error, it's a bad date format somewhere in the translations:

https://crowdin.com/translate/firefly-iii/141/en-de?filter=basic&value=0

I'll see what I can do in the new release, or at least see if I can do some verification on those strings (also for other languages).

**Comment by steakhutzeee** [comment]
Same issue here. In the transaction view the dates are in english while the language i set is different.

**Comment by JC5** [comment]
That's a different issue, I think. Can you add some screenshots?

**Comment by steakhutzeee** [comment]
> 
> 
> That's a different issue, I think. Can you add some screenshots?

Sure, will post them asap. I see the same layout as shown in @niklas2810 screenshots.

**Comment by Styleflix** [comment]
> 
> 
> This is something else. Looking at the error, it's a bad date format somewhere in the translations:
> 
> https://crowdin.com/translate/firefly-iii/141/en-de?filter=basic&value=0
> 
> I'll see what I can do in the new release, or at least see if I can do some verification on those strings (also for other languages).

I experience the same behavior - and use the same language. I tried switching to English and everything works fine again. So actually it really seems to be connected with the German translation.

**Comment by steakhutzeee** [comment]
> 
> 
> That's a different issue, I think. Can you add some screenshots?

Here a screenshot. Changing language to english does not solve the problem .

![firefly](https://user-images.githubusercontent.com/57228102/134408826-351ad6f9-71c2-46f6-8384-4f91a96f48f6.JPG)

**Comment by JC5** [comment]
Both of these issues should be fixed. :+1:

**Comment by JC5** [comment]
5.6.1 is out, and I believe this to be fixed. :+1:

**Comment by steakhutzeee** [comment]
> 5.6.1 is out, and I believe this to be fixed. 👍

Just pulled new docker image but it seems the same unfortunately.

**Comment by JC5** [comment]
You mentioned several issues in your reply, I'm not sure which one you're referring to. The date on the dashboard probably?

**Comment by steakhutzeee** [comment]
> You mentioned several issues in your reply, I'm not sure which one you're referring to. The date on the dashboard probably?

Both actually. Still see 'Treemap categories' and 'Treemap accounts'. Basically my screenshot remained the same.

**Comment by niklas2810** [comment]
> 5.6.1 is out, and I believe this to be fixed. :+1:

The transactions page and asset account list works again now (except for "Treemap categories" and "treemap accounts" on /transactions as mentioned above), but the transaction list for expense/withdrawal accounts is still broken.

**Comment by niklas2810** [comment]
Oh, and the transfer transactions page is still broken as well.. 😅

**Comment by Styleflix** [comment]
For me the issue about lists not loading content for transactions and subscriptions is fixed in version 5.6.1.
Different from what niklas2810 reported also for tranfer transactions. [I am using the German translation]

For the treemap thing I created a new issue report to exclude this topic from the bad date format issue

**Comment by niklas2810** [comment]
Huh, that's interesting, I'm using the German translation as well. I'll have a look today to see if it's still the same issue as before and maybe send a new screenshot.

**Comment by niklas2810** [comment]
![image](https://user-images.githubusercontent.com/30748216/134802046-bd4028fa-89d4-4081-a890-fe9cc437dcdb.png)
I can't spot any errors anymore in the console anymore. Is guess this page is still a WIP then, right @JC5 ?

**Comment by JC5** [comment]
It should at list show transactions and the "cache-miss" in the console is an indication it's doing something at least.

Is there a error msg in the Netwrok tab?

**Comment by niklas2810** [comment]
> Is there a error msg in the Netwrok tab?

Nope, only 200 OK responses over there, and I can't see any resources that can't be fetched/load infinitely.

**Comment by JC5** [comment]
Crap that would be easier :D 

Im on training this week but will do some research when i can. Thanks again for the support and extensive feedback.

**Comment by JC5** [comment]
Should be fixed in the next release!
