### ISSUE TITLE
Text for mass edit action button overlaid/duplicated

### ISSUE THREAD

**Issue by Impact123** [firefly-iii/firefly-iii#5101]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The `Actions` button to edit multiple transactions is illegible because phrases like `Edit selected individually` are duplicated/overlaid
![image](https://user-images.githubusercontent.com/899193/133958088-1552eeb7-5473-496d-b611-674df8b07b5d.png)
![image](https://user-images.githubusercontent.com/899193/133958222-5970fb9a-e723-4e21-96ec-70cda9b50170.png)

### Expected behaviour

Text should be legible

### Debug information

Not applicable. Reproduceable on official demo site.

### Steps to reproduce

1. Visit [one of the demo site's transaction pages](https://demo.firefly-iii.org/transactions/withdrawal)
2. Select a transaction
3. Click on the `Actions` button

**Comment by JC5** [comment]
Ah, nice find. I'll pick it up!

**Comment by JC5** [comment]
Fixed in the next release

**Comment by Impact123** [comment]
Thank you! I'll leave the issue open until it's released and report back once I've tested it if that's okay.

**Comment by JC5** [comment]
The demo site should be up to date, the issue may auto-close once the release is out.

**Comment by Impact123** [comment]
At the moment It's still reproducible on the demo page with the `Steps to reproduce`
![Screenshot from 2021-09-25 06-57-47](https://user-images.githubusercontent.com/899193/134759172-6389d2a9-117f-494d-a30c-e936f7c306aa.png)

**Comment by JC5** [comment]
Did you clear your cache?

**Comment by Impact123** [comment]
Yes. I even used incognito mode and a different browser to make sure.

**Comment by JC5** [comment]
Mmm. I visit this page: https://demo.firefly-iii.org/transactions/withdrawal

Select  a few transactions. Then use the top menu. The text is not duplicated. Chrome + Firefox on a Mac.

**Comment by Impact123** [comment]
It works as expected now. I can only assume that it was cached someone else. Maybe at the CDN for my region?

**Comment by JC5** [comment]
Mmmm, not a weird thought, my apologies for not checking. The demo site is behind Cloudflare.
