### ISSUE TITLE
[data-importer] 500 error when attempting to add bank account from Nordigen

### ISSUE THREAD

**Issue by gerjomarty** [firefly-iii/firefly-iii#5590]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The 500 exception happens on the callback from Nordigen to the Firefly III data importer.

### Expected behaviour

The bank account is connected successfully.

### Debug information

Output from /debug

Debug information generated at 2022-01-22 22:21:04 Europe/Amsterdam for Firefly III Data Importer version **0.7.0**.

| Scope | Version |
| --- | --- |
| FIDI | 0.7.0 |
| Build | 80, 22-01-2022 12:18:12 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/London |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0 |

Log

```
Now in entrypoint.sh for Firefly III Data Importer
Script:        1.5 (2021-12-05)
User:          'root'
Group:         'root'
Working dir:   '/var/www/html'
Build number:  80
Build date:    22-01-2022 12:18:12 CET
Firefly III data importer v0.7.0
PHP: cli 8.0.13 Linux
Will now run Apache web server:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
[Sat Jan 22 18:50:22.291976 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Sat Jan 22 18:50:22.292206 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[2022-01-22 19:51:38] production.DEBUG: Now in App\Http\Controllers\IndexController::index
[2022-01-22 19:51:38] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets
100.115.116.82 - - [22/Jan/2022:18:51:37 +0000] "GET / HTTP/1.1" 200 3222 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /fa/css/all.min.css HTTP/1.1" 200 13028 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /js/popper.min.js?version=0.7.0 HTTP/1.1" 200 7080 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /css/bootstrap-dark.min.css?version=0.7.0 HTTP/1.1" 200 31464 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /js/bootstrap.min.js?version=0.7.0 HTTP/1.1" 200 16729 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /js/jquery-3.6.0.min.js?version=0.7.0 HTTP/1.1" 200 31271 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /fa/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 79748 "http://firefly.<scrubbed domain>:8081/fa/css/all.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
[2022-01-22 19:51:38] production.DEBUG: Now at App\Http\Controllers\TokenController::doValidate
[2022-01-22 19:51:38] production.DEBUG: isReadyForNordigenStep("service-validation")
[2022-01-22 19:51:38] production.DEBUG: isReadyForNordigenStep("service-validation")
[2022-01-22 19:51:38] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:51:38] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:51:38] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate
[2022-01-22 19:51:38] production.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate
[2022-01-22 19:51:38] production.DEBUG: No Nordigen ID in hasId(), will return config variable.
[2022-01-22 19:51:38] production.DEBUG: No Nordigen key in hasKey(), will return config variable.
[2022-01-22 19:51:38] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.
[2022-01-22 19:51:38] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.
[2022-01-22 19:51:38] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken
[2022-01-22 19:51:38] production.DEBUG: No Nordigen refresh token, so return false.
[2022-01-22 19:51:38] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasExpiredRefreshToken
[2022-01-22 19:51:38] production.DEBUG: No refresh token, so return false.
[2022-01-22 19:51:38] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getNewTokenSet
[2022-01-22 19:51:38] production.DEBUG: setParameters
[2022-01-22 19:51:38] production.DEBUG: Result is {"result":"OK","message":null}
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /token/validate HTTP/1.1" 200 1139 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:39 +0000] "GET /favicon.ico HTTP/1.1" 200 279 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /validate/nordigen HTTP/1.1" 200 1124 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
100.115.116.82 - - [22/Jan/2022:18:51:38 +0000] "GET /validate/spectre HTTP/1.1" 200 1124 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
127.0.0.1 - - [22/Jan/2022:18:51:44 +0000] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.38 (Debian) (internal dummy connection)"
[2022-01-22 19:51:49] production.DEBUG: Now in App\Http\Controllers\IndexController::postIndex
[2022-01-22 19:51:49] production.DEBUG: nordigen is a valid flow, redirect to authenticate.
100.115.116.82 - - [22/Jan/2022:18:51:48 +0000] "POST / HTTP/1.1" 302 1943 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
[2022-01-22 19:51:49] production.DEBUG: Now in AuthenticateController, calling middleware.
[2022-01-22 19:51:49] production.DEBUG: isReadyForNordigenStep("authenticate")
[2022-01-22 19:51:49] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:51:49] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate
[2022-01-22 19:51:49] production.DEBUG: No Nordigen ID in hasId(), will return config variable.
[2022-01-22 19:51:49] production.DEBUG: No Nordigen key in hasKey(), will return config variable.
[2022-01-22 19:51:49] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken
[2022-01-22 19:51:49] production.DEBUG: No Nordigen refresh token, so return false.
[2022-01-22 19:51:49] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasExpiredRefreshToken
[2022-01-22 19:51:49] production.DEBUG: No refresh token, so return false.
[2022-01-22 19:51:49] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getNewTokenSet
100.115.116.82 - - [22/Jan/2022:18:51:49 +0000] "GET /authenticate HTTP/1.1" 302 1569 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
[2022-01-22 19:51:49] production.DEBUG: isReadyForNordigenStep("upload-files")
[2022-01-22 19:51:49] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:51:49] production.DEBUG: Now at App\Http\Controllers\Import\UploadController::index
[2022-01-22 19:51:49] production.DEBUG: Going to check directory for config files: /var/www/html/storage/configurations
[2022-01-22 19:51:49] production.DEBUG: List of files:
100.115.116.82 - - [22/Jan/2022:18:51:49 +0000] "GET /upload HTTP/1.1" 200 2506 "http://firefly.<scrubbed domain>:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
[2022-01-22 19:51:54] production.DEBUG: isReadyForNordigenStep("upload-files")
[2022-01-22 19:51:54] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:51:54] production.DEBUG: Now at App\Http\Controllers\Import\UploadController::upload
100.115.116.82 - - [22/Jan/2022:18:51:54 +0000] "POST /upload HTTP/1.1" 302 1619 "http://firefly.<scrubbed domain>:8081/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
[2022-01-22 19:51:54] production.DEBUG: isReadyForNordigenStep("nordigen-selection")
[2022-01-22 19:51:54] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:51:54] production.DEBUG: Now at App\Http\Controllers\Import\Nordigen\SelectionController::index
[2022-01-22 19:51:54] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken
[2022-01-22 19:51:54] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens
[2022-01-22 19:51:54] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken
[2022-01-22 19:51:54] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken
[2022-01-22 19:51:54] production.DEBUG: Nordigen token is valid until 2022-01-23 19:51:49
[2022-01-22 19:51:54] production.DEBUG: Nordigen token is valid.
[2022-01-22 19:51:54] production.DEBUG: Request parameters will be set to:
[2022-01-22 19:51:54] production.DEBUG: authenticatedGet(https://ob.nordigen.com/api/v2/institutions/?)
[2022-01-22 19:51:55] production.DEBUG: Return JSON result of authenticatedGet
100.115.116.82 - - [22/Jan/2022:18:51:54 +0000] "GET /import/selection HTTP/1.1" 200 71743 "http://firefly.<scrubbed domain>:8081/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
127.0.0.1 - - [22/Jan/2022:18:52:01 +0000] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.38 (Debian) (internal dummy connection)"
[2022-01-22 19:52:15] production.DEBUG: isReadyForNordigenStep("nordigen-selection")
[2022-01-22 19:52:15] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:52:15] production.DEBUG: Now at App\Http\Controllers\Import\Nordigen\SelectionController::postIndex
[2022-01-22 19:52:15] production.DEBUG: storeContent: Stored 678 bytes in file "f28d84962491feca04d6bba8c074eb772215fceaea8e4642b9e98dcb5e6cda78"
100.115.116.82 - - [22/Jan/2022:18:52:15 +0000] "POST /import/selection HTTP/1.1" 302 1670 "http://firefly.<scrubbed domain>:8081/import/selection" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
[2022-01-22 19:52:15] production.DEBUG: isReadyForNordigenStep("nordigen-link")
[2022-01-22 19:52:15] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:52:15] production.DEBUG: Now at App\Http\Controllers\Import\Nordigen\LinkController::build
[2022-01-22 19:52:15] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens
[2022-01-22 19:52:15] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken
[2022-01-22 19:52:15] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken
[2022-01-22 19:52:16] production.DEBUG: Nordigen token is valid until 2022-01-23 19:51:49
[2022-01-22 19:52:16] production.DEBUG: Nordigen token is valid.
[2022-01-22 19:52:16] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken
[2022-01-22 19:52:16] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens
[2022-01-22 19:52:16] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken
[2022-01-22 19:52:16] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken
[2022-01-22 19:52:16] production.DEBUG: Nordigen token is valid until 2022-01-23 19:51:49
[2022-01-22 19:52:16] production.DEBUG: Nordigen token is valid.
[2022-01-22 19:52:16] production.DEBUG: Request parameters will be set to:
[2022-01-22 19:52:16] production.DEBUG: Reference is 195c0754-90f1-4cd0-8423-23db8baa1196
[2022-01-22 19:52:16] production.DEBUG: Now at App\Services\Nordigen\Request\PostNewRequisitionRequest::post
[2022-01-22 19:52:16] production.DEBUG: Now at App\Services\Nordigen\Request\Request::authenticatedJsonPost
[2022-01-22 19:52:17] production.DEBUG: Got a new requisition with id ef536cdf-e430-4352-967f-4d97a102ca7a
[2022-01-22 19:52:17] production.DEBUG: Status: CR, returned reference: 195c0754-90f1-4cd0-8423-23db8baa1196
[2022-01-22 19:52:17] production.DEBUG: Will now redirect the user to https://ob.nordigen.com/psd2/start/<scrubbed token>/NATIONWIDE_NAIAGB21
100.115.116.82 - - [22/Jan/2022:18:52:15 +0000] "GET /import/link-nordigen/build HTTP/1.1" 302 1834 "http://firefly.<scrubbed domain>:8081/import/selection" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
[2022-01-22 19:53:46] production.DEBUG: isReadyForNordigenStep("nordigen-link")
[2022-01-22 19:53:46] production.DEBUG: isReadyForNordigenStep: Return true
[2022-01-22 19:53:46] production.DEBUG: Now at App\Http\Controllers\Import\Nordigen\LinkController::callback
[2022-01-22 19:53:46] production.DEBUG: Reference is
[2022-01-22 19:53:46] production.ERROR: App\Services\Shared\Configuration\Configuration::getRequisition(): Argument #1 ($key) must be of type string, null given, called in /var/www/html/app/Http/Controllers/Import/Nordigen/LinkController.php on line 135 {"exception":"[object] (TypeError(code: 0): App\\Services\\Shared\\Configuration\\Configuration::getRequisition(): Argument #1 ($key) must be of type string, null given, called in /var/www/html/app/Http/Controllers/Import/Nordigen/LinkController.php on line 135 at /var/www/html/app/Services/Shared/Configuration/Configuration.php:814)
[stacktrace]
#0 /var/www/html/app/Http/Controllers/Import/Nordigen/LinkController.php(135): App\\Services\\Shared\\Configuration\\Configuration->getRequisition()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\Nordigen\\LinkController->callback()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\LinkControllerMiddleware->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#39 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#46 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#47 {main}
"}
100.115.116.82 - - [22/Jan/2022:18:53:46 +0000] "GET /import/link-nordigen/callback HTTP/1.1" 500 7717 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:96.0) Gecko/20100101 Firefox/96.0"
```

### Additional info

Sorry, wish I was able to dive into the source code a little more to provide more context.

It seems like the call to the request to get the reference in the callback function is unexpectedly returning `NULL`. See https://github.com/firefly-iii/data-importer/blob/485af7d65d405e8ad61e3db03dd2ef9da0b8b26a/app/Http/Controllers/Import/Nordigen/LinkController.php#L129 .

Please let me know if you need any more info to help with debugging.

**Comment by JC5** [comment]
I see you're submitting no timezone (TZ) or an empty one when running the importer, is that on purpose?

I've pushed some changes to `fireflyiii/data-importer:develop`, could you run the importer with that image and try again? If anything, the importer will error out, and I'd like you to share the URL with me (can also be done over email, james@firefly-iii.org).

**Comment by gerjomarty** [comment]
> I see you're submitting no timezone (TZ) or an empty one when running the importer, is that on purpose?

No, it's not. I'd been running the importer with a minimal set of environment variables. Have changed this by just importing all of the app environment variables into the importer (as well as the importer specific ones) and confirmed I'm still seeing the issue in 0.7.0. Thanks for the heads up on that.

Still seeing the issue with the `develop` image, will send you the details over email. Thank you!

**Comment by JC5** [comment]
Thanks. I've CC'd @Nordigen support, and we'll have to see what it could be.

**Comment by JC5** [comment]
As discussed over email, it might have have been a fluke. Closing for now.
