### ISSUE TITLE
Editing accounts makes them inactive, can't activate

### ISSUE THREAD

**Issue by Elroban** [firefly-iii/firefly-iii#726]
Hi,

When I change something on my accounts, for example the starting balance, the account gets inactivated.
After that I can't seem to get it activated again as it won't save the enabling of the checkbox.
I have to manually edit the data in the table accounts.

Running version 4.6.3 and I can't seem to reproduce this in the demo environment.
I will try version 4.6.3.1 first.

**Comment by JC5** [comment]
This is a bug and should be fixed in 4.6.3.1 indeed. Please let me know when it is still there!

**Comment by Elroban** [comment]
As I run Firefly-iii in docker:
- I pulled the latest GIT
- Built a new docker image
- Run a new docker container
- Upgraded my db container with the php artisan firefly:upgrade-database command
My interface shows 4.6.3.1.

Though the bug still resists in my environment so there should be another thing different compared to your demo.

**Comment by JC5** [comment]
I was wrong and I apologize. [The fix](https://github.com/firefly-iii/firefly-iii/commit/99a0bf1286e23f4159e67716c99e2d0042e68afe) is not yet live. It will be in the next release, which will require PHP7.1

**Comment by JC5** [comment]
Release is live.
