### ISSUE TITLE
"Generating new OAuth keys" after each container restart

### ISSUE THREAD

**Issue by PeteS4** [firefly-iii/firefly-iii#7630]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Every restart of the firefly container logs the following lines:
```
Jun 10 16:23:26 firefly[28206]: Generating new OAuth keys...
Jun 10 16:23:28 firefly[28206]: Encryption keys generated successfully.
Jun 10 16:23:28 firefly[28206]: Personal access client created successfully.
Jun 10 16:23:28 firefly[28206]: Client ID: 11
Jun 10 16:23:28 firefly[28206]: Client secret: ...
Jun 10 16:23:28 firefly[28206]: Password grant client created successfully.
Jun 10 16:23:28 firefly[28206]: Client ID: 12
Jun 10 16:23:28 firefly[28206]: Client secret: ...
Jun 10 16:23:29 firefly[28206]: Updated version.
```
and I have to recreate all access tokens. I'm aware of #4436 and #3386 but they are closed and for me the problem still exists with v6.0.11

### Debug information

Debug information generated at 2023-06-10 16:35:33 Europe/Berlin for Firefly III version **6.0.11**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.11 |
| Firefly III API | 2.0.3 |
| Build | 490, 27-05-2023 07:21:11 CEST |
| Base Build | 3, 29-04-2023 14:45:54 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.5` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | sqlite |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start |  |
| Session end |  |
| Session first |  |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0 |

### Expected behaviour

The logs should say `Restored OAuth keys from database.` and previously registered clients should be able to authenticate.

### Steps to reproduce

1. register personal access token
2. restart docker container
3. try authenticating with a third party client

### Additional info

Directly above the `Generating new OAuth keys` line, every container restart logs a `bccomp(): Argument #1 ($num1) is not well-formed` error, but that more likely seems to be related to `Now executing firefly-iii:report-sum`, as the stack trace starts with `ReportSum.php`.

**Comment by JC5** [comment]
Thanks for reporting!

- Do you regenerate the access tokens because you think they won't work, or did you test this?
- Could you share the stack trace of that other error?

**Comment by PeteS4** [comment]
Sure. It happens twice during the startup sequence, so I attached the whole log, just in case:

```
Jun 10 16:22:59 systemd[1]: Starting firefly.service - Podman firefly.service...
Jun 10 16:22:59 podman[27904]: 2023-06-10 16:22:59.79216188 +0200 CEST m=+0.441375618 image pull 9fc5db0a750ed153a283daceaa186e1cd5bf692ff65f971e6f7d21d9c1e860e7 docker.io/fireflyiii/core:latest
Jun 10 16:22:59 podman[27904]: 2023-06-10 16:22:59.913745595 +0200 CEST m=+0.562959351 container create 1bb136b0c3bd47568b8ffa2f48006dda37a89355e51c3081fec698206f064a68 (image=docker.io/fireflyiii/core:latest, name=firefly, traefik.http.routers.firefly.entrypoints=web-secure, traefik.http.services.firefly.loadbalancer.server.port=8080, traefik.enable=true, io.containers.autoupdate=registry, PODMAN_SYSTEMD_UNIT=firefly.service, maintainer=james@firefly-iii.org, traefik.http.routers.firefly.tls.certresolver=dockerCertResolver, traefik.http.routers.firefly.tls=true, build_version=4.3)
Jun 10 16:23:00 dnsmasq[28154]: started, version 2.89 cachesize 150
Jun 10 16:23:00 dnsmasq[28154]: compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset no-nftset auth cryptohash DNSSEC loop-detect inotify dumpfile
Jun 10 16:23:00 dnsmasq[28154]: using only locally-known addresses for dns.podman
Jun 10 16:23:00 dnsmasq[28154]: reading /etc/resolv.conf
Jun 10 16:23:00 dnsmasq[28154]: using nameserver 127.0.0.53#53
Jun 10 16:23:00 dnsmasq[28154]: using only locally-known addresses for dns.podman
Jun 10 16:23:00 dnsmasq[28154]: read /run/containers/cni/dnsname/firefly/addnhosts - 6 names
Jun 10 16:23:00 podman[27904]: 2023-06-10 16:23:00.891134727 +0200 CEST m=+1.540348483 container init 1bb136b0c3bd47568b8ffa2f48006dda37a89355e51c3081fec698206f064a68 (image=docker.io/fireflyiii/core:latest, name=firefly, PODMAN_SYSTEMD_UNIT=firefly.service, traefik.http.routers.firefly.entrypoints=web-secure, maintainer=james@firefly-iii.org, traefik.http.routers.firefly.tls=true, build_version=4.3, io.containers.autoupdate=registry, traefik.http.routers.firefly.tls.certresolver=dockerCertResolver, traefik.http.services.firefly.loadbalancer.server.port=8080, traefik.enable=true)
Jun 10 16:23:00 systemd[1]: Started firefly.service - Podman firefly.service.
Jun 10 16:23:00 firefly[28206]: Now in entrypoint.sh for Firefly III
Jun 10 16:23:00 firefly[28206]: Script:       1.0.22 (2023-04-16)
Jun 10 16:23:00 firefly[28206]: User:         'root'
Jun 10 16:23:00 podman[27904]: 2023-06-10 16:23:00.974642433 +0200 CEST m=+1.623856190 container start 1bb136b0c3bd47568b8ffa2f48006dda37a89355e51c3081fec698206f064a68 (image=docker.io/fireflyiii/core:latest, name=firefly, traefik.http.routers.firefly.entrypoints=web-secure, build_version=4.3, traefik.http.routers.firefly.tls.certresolver=dockerCertResolver, traefik.enable=true, io.containers.autoupdate=registry, PODMAN_SYSTEMD_UNIT=firefly.service, traefik.http.services.firefly.loadbalancer.server.port=8080, traefik.http.routers.firefly.tls=true, maintainer=james@firefly-iii.org)
Jun 10 16:23:00 podman[27904]: 1bb136b0c3bd47568b8ffa2f48006dda37a89355e51c3081fec698206f064a68
Jun 10 16:23:01 firefly[28206]: Group:        'root'
Jun 10 16:23:01 firefly[28206]: Working dir:  '/var/www/html'
Jun 10 16:23:01 firefly[28206]: Build number:  490
Jun 10 16:23:01 firefly[28206]: Build date:    27-05-2023 07:21:11 CEST
Jun 10 16:23:01 firefly[28206]: Now parsing _FILE variables.
Jun 10 16:23:01 firefly[28206]: done!
Jun 10 16:23:01 firefly[28206]: Touch DB file (if SQLite)...
Jun 10 16:23:01 firefly[28206]: Touched!
Jun 10 16:23:01 firefly[28206]: Dump auto load...
Jun 10 16:23:03 firefly[28206]: Generating optimized autoload files
Jun 10 16:23:16 firefly[28206]: > Illuminate\Foundation\ComposerScripts::postAutoloadDump
Jun 10 16:23:16 firefly[28206]: Generated optimized autoload files containing 6313 classes
Jun 10 16:23:16 firefly[28206]: Discover packages...
Jun 10 16:23:17 firefly[28206]: 
Jun 10 16:23:17 firefly[28206]:    INFO  Discovering packages.  
Jun 10 16:23:17 firefly[28206]: 
Jun 10 16:23:17 firefly[28206]:   diglactic/laravel-breadcrumbs ......................................... DONE
Jun 10 16:23:17 firefly[28206]:   jc5/google2fa-laravel ................................................. DONE
Jun 10 16:23:17 firefly[28206]:   laravel/passport ...................................................... DONE
Jun 10 16:23:17 firefly[28206]:   laravel/sanctum ....................................................... DONE
Jun 10 16:23:17 firefly[28206]:   laravel/slack-notification-channel .................................... DONE
Jun 10 16:23:17 firefly[28206]:   laravel/ui ............................................................ DONE
Jun 10 16:23:17 firefly[28206]:   laravelcollective/html ................................................ DONE
Jun 10 16:23:17 firefly[28206]:   nesbot/carbon ......................................................... DONE
Jun 10 16:23:17 firefly[28206]:   nunomaduro/collision .................................................. DONE
Jun 10 16:23:17 firefly[28206]:   nunomaduro/termwind ................................................... DONE
Jun 10 16:23:17 firefly[28206]:   rcrowe/twigbridge ..................................................... DONE
Jun 10 16:23:17 firefly[28206]:   spatie/laravel-ignition ............................................... DONE
Jun 10 16:23:17 firefly[28206]:   therobfonz/laravel-mandrill-driver .................................... DONE
Jun 10 16:23:17 firefly[28206]: 
Jun 10 16:23:17 firefly[28206]: Current working dir is '/var/www/html'
Jun 10 16:23:17 firefly[28206]: Wait for the database. You may see an error about an 'aborted connection', this is normal.
Jun 10 16:23:17 firefly[28206]: Wait another 5 seconds in case the DB needs to boot.
Jun 10 16:23:22 firefly[28206]: Done waiting for the DB to boot.
Jun 10 16:23:22 firefly[28206]: Will not build the locales...
Jun 10 16:23:22 firefly[28206]: Run various artisan commands...
Jun 10 16:23:22 firefly[28206]: Running migration commands...
Jun 10 16:23:23 firefly[28206]: CreateDB does not apply to "sqlite", skipped.
Jun 10 16:23:23 firefly[28206]: Current working dir is '/var/www/html'
Jun 10 16:23:23 firefly[28206]: Running upgrade commands...
Jun 10 16:23:23 firefly[28206]: Now seeding the database...
Jun 10 16:23:23 firefly[28206]:    INFO  Nothing to migrate.  
Jun 10 16:23:23 firefly[28206]: 
Jun 10 16:23:23 firefly[28206]:    INFO  Seeding database.  
Jun 10 16:23:23 firefly[28206]: 
Jun 10 16:23:23 firefly[28206]:   Database\Seeders\AccountTypeSeeder ................................. RUNNING  
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\AccountTypeSeeder ........................... 30.98 ms DONE  
Jun 10 16:23:24 firefly[28206]: 
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\TransactionCurrencySeeder ......................... RUNNING  
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\TransactionCurrencySeeder ................... 50.63 ms DONE  
Jun 10 16:23:24 firefly[28206]: 
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\TransactionTypeSeeder ............................. RUNNING  
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\TransactionTypeSeeder ........................ 7.07 ms DONE  
Jun 10 16:23:24 firefly[28206]: 
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\PermissionSeeder .................................. RUNNING  
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\PermissionSeeder ............................. 2.93 ms DONE  
Jun 10 16:23:24 firefly[28206]: 
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\LinkTypeSeeder .................................... RUNNING  
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\LinkTypeSeeder ............................... 5.33 ms DONE  
Jun 10 16:23:24 firefly[28206]: 
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\ConfigSeeder ...................................... RUNNING  
Jun 10 16:23:24 firefly[28206]: [2023-06-10 16:23:24] production.WARNING: Database entry exists. Update to latest version (19)  
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\ConfigSeeder ................................ 17.52 ms DONE  
Jun 10 16:23:24 firefly[28206]: 
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\UserRoleSeeder .................................... RUNNING  
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\UserRoleSeeder .............................. 10.26 ms DONE  
Jun 10 16:23:24 firefly[28206]: 
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\ExchangeRateSeeder ................................ RUNNING  
Jun 10 16:23:24 firefly[28206]:   Database\Seeders\ExchangeRateSeeder ......................... 552.51 ms DONE  
Jun 10 16:23:24 firefly[28206]: 
Jun 10 16:23:24 firefly[28206]: Fix PostgreSQL sequences.
Jun 10 16:23:24 firefly[28206]: Command executed successfully.
Jun 10 16:23:24 firefly[28206]: Now decrypting the database (if necessary)...
Jun 10 16:23:24 firefly[28206]: Going to decrypt the database.
Jun 10 16:23:24 firefly[28206]: No decryption required for table "accounts".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "attachments".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "bills".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "budgets".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "categories".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "piggy_banks".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "preferences".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "tags".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "transaction_journals".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "transactions".
Jun 10 16:23:24 firefly[28206]: No decryption required for table "journal_links".
Jun 10 16:23:24 firefly[28206]: Done!
Jun 10 16:23:24 firefly[28206]: Done!
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:transaction-identifiers
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:migrate-to-groups
Jun 10 16:23:24 firefly[28206]: Database already seems to be migrated.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:account-currencies
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:transfer-currencies
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:other-currencies
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:migrate-notes
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:migrate-attachments
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:bills-to-rules
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:bl-currency
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:cc-liabilities
Jun 10 16:23:24 firefly[28206]: No incorrectly stored credit card liabilities.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:back-to-journals
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:rename-account-meta
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:migrate-recurrence-meta
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:migrate-tag-locations
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:migrate-recurrence-type
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:upgrade-liabilities
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:liabilities-600
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Now executing firefly-iii:budget-limit-periods
Jun 10 16:23:24 firefly[28206]: This command has already been executed.
Jun 10 16:23:24 firefly[28206]: Running verification commands...
Jun 10 16:23:25 firefly[28206]: Handle Firefly III database correction commands.
Jun 10 16:23:25 firefly[28206]: Now executing command "firefly-iii:fix-piggies"
Jun 10 16:23:25 firefly[28206]: All piggy bank events are correct.
Jun 10 16:23:25 firefly[28206]: Verified the content of 0 piggy bank events in 0.03 seconds.
Jun 10 16:23:25 firefly[28206]: Now executing command "firefly-iii:create-link-types"
Jun 10 16:23:25 firefly[28206]: All link types OK!
Jun 10 16:23:25 firefly[28206]: Verified link types in 0.01 seconds
Jun 10 16:23:25 firefly[28206]: Now executing command "firefly-iii:create-access-tokens"
Jun 10 16:23:25 firefly[28206]: All access tokens OK!
Jun 10 16:23:25 firefly[28206]: Verify access tokens in 0.01 seconds.
Jun 10 16:23:25 firefly[28206]: Now executing command "firefly-iii:remove-bills"
Jun 10 16:23:25 firefly[28206]: All transaction journals have correct bill information.
Jun 10 16:23:25 firefly[28206]: Verified bills / journals in 0.11 seconds
Jun 10 16:23:25 firefly[28206]: Now executing command "firefly-iii:fix-amount-pos-neg"
Jun 10 16:23:25 firefly[28206]: Correct: All auto budget amounts are positive.
Jun 10 16:23:25 firefly[28206]: Correct: All available budget amounts are positive.
Jun 10 16:23:25 firefly[28206]: Correct: All bill amounts are positive.
Jun 10 16:23:25 firefly[28206]: Correct: All budget limit amounts are positive.
Jun 10 16:23:25 firefly[28206]: Correct: All currency exchange rates are positive.
Jun 10 16:23:25 firefly[28206]: Correct: All piggy bank repetition amounts are positive.
Jun 10 16:23:25 firefly[28206]: Correct: All piggy bank amounts are positive.
Jun 10 16:23:25 firefly[28206]: Correct: All recurring transaction amounts are positive.
Jun 10 16:23:25 firefly[28206]: Correct: All rule trigger amounts are positive.
Jun 10 16:23:25 firefly[28206]: Now executing command "firefly-iii:enable-currencies"
Jun 10 16:23:25 firefly[28206]: 1 different currencies are currently in use.
Jun 10 16:23:25 firefly[28206]: All currencies are correctly enabled or disabled.
Jun 10 16:23:25 firefly[28206]: Verified currencies in 0.18 seconds.
Jun 10 16:23:25 firefly[28206]: Now executing command "firefly-iii:fix-transfer-budgets"
Jun 10 16:23:25 firefly[28206]: No invalid budget/journal entries.
Jun 10 16:23:25 firefly[28206]: Verified budget/journals in 0 seconds.
Jun 10 16:23:25 firefly[28206]: Now executing command "firefly-iii:fix-uneven-amount"
Jun 10 16:23:25 firefly[28206]: [2023-06-10 16:23:25] production.ERROR: bccomp(): Argument #1 ($num1) is not well-formed {"exception":"[object] (ValueError(code: 0): bccomp(): Argument #1 ($num1) is not well-formed at /var/www/html/app/Console/Commands/Correction/FixUnevenAmount.php:68)
Jun 10 16:23:25 firefly[28206]: [stacktrace]
Jun 10 16:23:25 firefly[28206]: #0 /var/www/html/app/Console/Commands/Correction/FixUnevenAmount.php(68): bccomp()
Jun 10 16:23:25 firefly[28206]: #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Correction\\FixUnevenAmount->handle()
Jun 10 16:23:25 firefly[28206]: #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
Jun 10 16:23:25 firefly[28206]: #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
Jun 10 16:23:25 firefly[28206]: #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
Jun 10 16:23:25 firefly[28206]: #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
Jun 10 16:23:25 firefly[28206]: #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
Jun 10 16:23:25 firefly[28206]: #7 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
Jun 10 16:23:25 firefly[28206]: #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
Jun 10 16:23:25 firefly[28206]: #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
Jun 10 16:23:25 firefly[28206]: #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
Jun 10 16:23:25 firefly[28206]: #11 /var/www/html/app/Console/Commands/Correction/CorrectDatabase.php(90): Illuminate\\Console\\Command->call()
Jun 10 16:23:25 firefly[28206]: #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Correction\\CorrectDatabase->handle()
Jun 10 16:23:25 firefly[28206]: #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
Jun 10 16:23:25 firefly[28206]: #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
Jun 10 16:23:25 firefly[28206]: #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
Jun 10 16:23:25 firefly[28206]: #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
Jun 10 16:23:25 firefly[28206]: #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
Jun 10 16:23:25 firefly[28206]: #18 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
Jun 10 16:23:25 firefly[28206]: #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
Jun 10 16:23:25 firefly[28206]: #20 /var/www/html/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
Jun 10 16:23:25 firefly[28206]: #21 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
Jun 10 16:23:25 firefly[28206]: #22 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
Jun 10 16:23:25 firefly[28206]: #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
Jun 10 16:23:25 firefly[28206]: #24 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
Jun 10 16:23:25 firefly[28206]: #25 {main}
Jun 10 16:23:25 firefly[28206]: "} 
Jun 10 16:23:25 firefly[28206]: 
Jun 10 16:23:25 firefly[28206]:    ValueError 
Jun 10 16:23:25 firefly[28206]: 
Jun 10 16:23:25 firefly[28206]:   bccomp(): Argument #1 ($num1) is not well-formed
Jun 10 16:23:25 firefly[28206]: 
Jun 10 16:23:25 firefly[28206]:   at app/Console/Commands/Correction/FixUnevenAmount.php:68
Jun 10 16:23:25 firefly[28206]:      64▕                       ->whereNull('deleted_at')
Jun 10 16:23:25 firefly[28206]:      65▕                       ->get(['transaction_journal_id', DB::raw('SUM(amount) AS the_sum')]);
Jun 10 16:23:25 firefly[28206]:      66▕         /** @var stdClass $entry */
Jun 10 16:23:25 firefly[28206]:      67▕         foreach ($journals as $entry) {
Jun 10 16:23:25 firefly[28206]:   ➜  68▕             if (0 !== bccomp((string)$entry->the_sum, '0')) {
Jun 10 16:23:25 firefly[28206]:      69▕                 $message = sprintf('Sum of journal #%d is %s instead of zero.', $entry->transaction_journal_id, $entry->the_sum);
Jun 10 16:23:25 firefly[28206]:      70▕                 $this->warn($message);
Jun 10 16:23:25 firefly[28206]:      71▕                 app('log')->warning($message);
Jun 10 16:23:25 firefly[28206]:      72▕                 $this->fixJournal((int)$entry->transaction_journal_id);
Jun 10 16:23:25 firefly[28206]: 
Jun 10 16:23:25 firefly[28206]:   1   app/Console/Commands/Correction/FixUnevenAmount.php:68
Jun 10 16:23:25 firefly[28206]:       +10 vendor frames 
Jun 10 16:23:25 firefly[28206]: 
Jun 10 16:23:25 firefly[28206]:   12  app/Console/Commands/Correction/CorrectDatabase.php:90
Jun 10 16:23:25 firefly[28206]:       Illuminate\Console\Command::call()
Jun 10 16:23:25 firefly[28206]: 
Jun 10 16:23:25 firefly[28206]: Running report commands...
Jun 10 16:23:26 firefly[28206]: Now executing firefly-iii:create-group-memberships
Jun 10 16:23:26 firefly[28206]: Validated group memberships in 0.05 seconds.
Jun 10 16:23:26 firefly[28206]: Now executing firefly-iii:report-empty-objects
Jun 10 16:23:26 firefly[28206]: Report on empty objects finished in 0.1 seconds
Jun 10 16:23:26 firefly[28206]: Now executing firefly-iii:report-sum
Jun 10 16:23:26 firefly[28206]: [2023-06-10 16:23:26] production.ERROR: bccomp(): Argument #1 ($num1) is not well-formed {"exception":"[object] (ValueError(code: 0): bccomp(): Argument #1 ($num1) is not well-formed at /var/www/html/app/Console/Commands/Integrity/ReportSum.php:72)
Jun 10 16:23:26 firefly[28206]: [stacktrace]
Jun 10 16:23:26 firefly[28206]: #0 /var/www/html/app/Console/Commands/Integrity/ReportSum.php(72): bccomp()
Jun 10 16:23:26 firefly[28206]: #1 /var/www/html/app/Console/Commands/Integrity/ReportSum.php(55): FireflyIII\\Console\\Commands\\Integrity\\ReportSum->reportSum()
Jun 10 16:23:26 firefly[28206]: #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Integrity\\ReportSum->handle()
Jun 10 16:23:26 firefly[28206]: #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
Jun 10 16:23:26 firefly[28206]: #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
Jun 10 16:23:26 firefly[28206]: #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
Jun 10 16:23:26 firefly[28206]: #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
Jun 10 16:23:26 firefly[28206]: #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
Jun 10 16:23:26 firefly[28206]: #8 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
Jun 10 16:23:26 firefly[28206]: #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
Jun 10 16:23:26 firefly[28206]: #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
Jun 10 16:23:26 firefly[28206]: #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
Jun 10 16:23:26 firefly[28206]: #12 /var/www/html/app/Console/Commands/Integrity/ReportIntegrity.php(68): Illuminate\\Console\\Command->call()
Jun 10 16:23:26 firefly[28206]: #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Integrity\\ReportIntegrity->handle()
Jun 10 16:23:26 firefly[28206]: #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
Jun 10 16:23:26 firefly[28206]: #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
Jun 10 16:23:26 firefly[28206]: #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
Jun 10 16:23:26 firefly[28206]: #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
Jun 10 16:23:26 firefly[28206]: #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
Jun 10 16:23:26 firefly[28206]: #19 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
Jun 10 16:23:26 firefly[28206]: #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
Jun 10 16:23:26 firefly[28206]: #21 /var/www/html/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
Jun 10 16:23:26 firefly[28206]: #22 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
Jun 10 16:23:26 firefly[28206]: #23 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
Jun 10 16:23:26 firefly[28206]: #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
Jun 10 16:23:26 firefly[28206]: #25 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
Jun 10 16:23:26 firefly[28206]: #26 {main}
Jun 10 16:23:26 firefly[28206]: "} 
Jun 10 16:23:26 firefly[28206]: 
Jun 10 16:23:26 firefly[28206]:    ValueError 
Jun 10 16:23:26 firefly[28206]: 
Jun 10 16:23:26 firefly[28206]:   bccomp(): Argument #1 ($num1) is not well-formed
Jun 10 16:23:26 firefly[28206]: 
Jun 10 16:23:26 firefly[28206]:   at app/Console/Commands/Integrity/ReportSum.php:72
Jun 10 16:23:26 firefly[28206]:      68▕ 
Jun 10 16:23:26 firefly[28206]:      69▕         /** @var User $user */
Jun 10 16:23:26 firefly[28206]:      70▕         foreach ($userRepository->all() as $user) {
Jun 10 16:23:26 firefly[28206]:      71▕             $sum = (string)$user->transactions()->sum('amount');
Jun 10 16:23:26 firefly[28206]:   ➜  72▕             if (0 !== bccomp($sum, '0')) {
Jun 10 16:23:26 firefly[28206]:      73▕                 $message = sprintf('Error: Transactions for user #%d (%s) are off by %s!', $user->id, $user->email, $sum);
Jun 10 16:23:26 firefly[28206]:      74▕                 $this->error($message);
Jun 10 16:23:26 firefly[28206]:      75▕             }
Jun 10 16:23:26 firefly[28206]:      76▕             if (0 === bccomp($sum, '0')) {
Jun 10 16:23:26 firefly[28206]: 
Jun 10 16:23:26 firefly[28206]:   1   app/Console/Commands/Integrity/ReportSum.php:72
Jun 10 16:23:26 firefly[28206]: 
Jun 10 16:23:26 firefly[28206]:   2   app/Console/Commands/Integrity/ReportSum.php:55
Jun 10 16:23:26 firefly[28206]:       FireflyIII\Console\Commands\Integrity\ReportSum::reportSum()
Jun 10 16:23:26 firefly[28206]: 
Jun 10 16:23:26 firefly[28206]: Generating new OAuth keys...
Jun 10 16:23:28 firefly[28206]: Encryption keys generated successfully.
Jun 10 16:23:28 firefly[28206]: Personal access client created successfully.
Jun 10 16:23:28 firefly[28206]: Client ID: 11
Jun 10 16:23:28 firefly[28206]: Client secret: ...
Jun 10 16:23:28 firefly[28206]: Password grant client created successfully.
Jun 10 16:23:28 firefly[28206]: Client ID: 12
Jun 10 16:23:28 firefly[28206]: Client secret: ...
Jun 10 16:23:29 firefly[28206]: Updated version.
Jun 10 16:23:32 firefly[28206]: +------------------------------------------------------------------------------+
Jun 10 16:23:32 firefly[28206]: |                                                                              |
Jun 10 16:23:32 firefly[28206]: | Thank you for installing Firefly III, v6.0.11!                               |
Jun 10 16:23:32 firefly[28206]: | There are no extra installation instructions.                                |
Jun 10 16:23:32 firefly[28206]: | Firefly III should be ready for use.                                         |
Jun 10 16:23:32 firefly[28206]: |                                                                              |
Jun 10 16:23:32 firefly[28206]: +------------------------------------------------------------------------------+
Jun 10 16:23:32 firefly[28206]: You can safely ignore the error about the 'fully qualified domain name'.
Jun 10 16:23:32 firefly[28206]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.89.4.3. Set the 'ServerName' directive globally to suppress this message
Jun 10 16:23:32 firefly[28206]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.89.4.3. Set the 'ServerName' directive globally to suppress this message
Jun 10 16:23:32 firefly[28206]: [Sat Jun 10 16:23:32.446477 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.56 (Debian) configured -- resuming normal operations
Jun 10 16:23:32 firefly[28206]: [Sat Jun 10 16:23:32.446603 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

```

**Comment by JC5** [comment]
Could you please delete your Firefly III instance, drop the local image (use either `docker prune` or `docker image`) and recreate the container? If you can, use the `develop` tag. I've added some code that should fix the issue.

**Comment by PeteS4** [comment]
Thank you, that seems to have fixed it! I had to recreate the tokens one more time after switching to the `develop` tag, but now it has survived multiple container restarts. :+1:

**Comment by JC5** [comment]
Great! No other warnings or errors in your logs?

**Comment by PeteS4** [comment]
Well, the two `bccomp(): Argument #1 ($num1) is not well-formed` errors still occur. But that doesn't seem to have any negative consequence (anymore)..

**Comment by JC5** [comment]
Haha, ok I will add some debug and give you instructions because that is not supposed to happen. Stay tuned.

**Comment by timendum** [comment]
Sorry if I'm wrong, but I run my container with `DKR_RUN_PASSPORT_INSTALL=false` to keep old keys valid. It's the same matter?

**Comment by JC5** [comment]
That should (no longer) be necessary, but if it works, it works!
