### ISSUE TITLE
All account charts show a horizontal line

### ISSUE THREAD

**Issue by avee87** [firefly-iii/firefly-iii#9797]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since upgrading to 6.2.x and enabling currency conversion all account charts seem to display a horizontal line.

Example:
<img width="1173" alt="Image" src="https://github.com/user-attachments/assets/0606da1b-f11d-4394-b33e-6524f19fe6fd" />
This account has transactions pretty much daily. Note that amount on the chart does not even match the current total displayed above.

This seems to affect every single account I have.

Issue seems to be reproduced on demo instance: https://demo.firefly-iii.org/accounts/show/1
<img width="1176" alt="Image" src="https://github.com/user-attachments/assets/d5eee239-f772-4f3f-8a82-909108c6a1e0" />

### Debug information

Debug information generated at 2025-02-09 13:12:24 for Firefly III version **v6.2.5**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.2.5 / <span>#</span>25 (expects <span>#</span>25)</td></tr><tr><td>PHP version</td><td>8.4.3 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>104857600 (100 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/London + Europe/London</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver, session driver</td><td>file, file</td></tr><tr><td>Default language and locale</td><td>en_GB + equal</td></tr><tr><td>Trusted proxies</td><td><code>**</code></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2025-02-09 00:00:00 (13 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr><tr><td>Exchange rates</td><td>Enabled, downloads enabled</td></tr><tr><td>RB-column</td><td>Disabled</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span></td></tr><tr><td>Native currency</td><td>GBP</td></tr><tr><td>Convert to native currency?</td><td>Enabled</td></tr><tr><td>Session start</td><td>2025-01-01 00:00:00</td></tr><tr><td>Session end</td><td>2025-02-09 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

I see what you mean, that's probably a bug! I just can't seem to get those right lol. 

Cheers,
James

**Comment by nebster9k** [comment]
Hi!
I applied your fix from 41ad35880dea57a0cec6828757cdd01d842e4149 to v6.2.5, the problem was solved, but only for the summary chart of accounts. The problem remained on the charts in accounts with native currency, a horizontal line with the value relevant at the start of the chart.

Best Regards

**Comment by JC5** [comment]
Thanks for helping me debug this!

**Comment by JC5** [comment]
I believe this issue is now fixed, I was not able to reproduce anymore it in my tests. Thanks everybody!

**Comment by nebster9k** [comment]
Hi again! I'm afraid not exactly...
I took the latest development release from ee260a3df718177ca95ef5de04ef2495d866b498, judging by the commit history - the related fixes are already applied "as is", and the problem is still there...
Below I provide screenshots with steps to reproduce, and if you want, I can provide access to the domain on which it is currently deployed in this exact state

## Screenshots
This is what an account looks like with the "display native amounts" feature `enabled`
![Image](https://github.com/user-attachments/assets/638dbccf-f058-4c75-9340-0751539eab74)

And this is how it looks with the "display native amounts" feature `disabled`
![Image](https://github.com/user-attachments/assets/d097ee81-9935-4c14-90d5-bde2f2dff932)

## Configuration
| tool | version |
|-|-|
| ubuntu | 22.04.5 |
| apache | 2.4.52 |
| php | 8.4 |
| postgresql | 14.15 |
| firefly | develop/2025-02-11 |

## Reproduction order
1. Create a new one psql user and database named firefly both
2. Obtaining an image 
```
sudo mkdir /var/www/<domain_name> && cd /var/www/<domain_name>
sudo wget https://github.com/firefly-iii/firefly-iii/releases/download/develop-20250211/FireflyIII-develop.zip
sudo unzip -q FireflyIII-develop.zip && sudo rm FireflyIII-develop.zip
sudo chown -R www-data:www-data /var/www/<domain_name> && sudo chmod -R 775 /var/www/<domain_name>/storage
sudo cp .env.example .env && sudo chown www-data:www-data .env
```
3. Set `ENABLE_EXCHANGE_RATES` to `true`, set db/email settings, locales to en_US, etc.
4. Init the database
```
sudo -u www-data /usr/bin/php /var/www/<domain_name>/artisan firefly-iii:upgrade-database
sudo -u www-data /usr/bin/php /var/www/<domain_name>/artisan firefly-iii:correct-database
sudo -u www-data /usr/bin/php /var/www/<domain_name>/artisan firefly-iii:report-integrity
sudo -u www-data /usr/bin/php /var/www/<domain_name>/artisan firefly-iii:laravel-passport-keys
```
### Reproduce
5. Login:
5.1. Go to `https://<domain_name>`, first login / register user

6. Settings
6.1. `Currencies` -> enable one or more non-native currencies (e.g. usd)
6.2. `Exchange rates` -> ensure for at least one rate is specified for each enabled currencies with `[now - 1 month] date` or earlier, with a rate 1.5, to make changes visible when scaling
6.3. `Preferences` -> `display native amounts` = `true` -> save

7. Accounts
7.1. `Asset accounts` -> create default asset account for native currency (euro by default) - with `opening balance 600`, `opening balance date [now - 2 weeks]`, `virtual balance 0`
7.2. `Asset accounts` -> create default asset account (or cash wallet, doesn't matter) for other currency (e.g. usd or custom) - with `opening balance 100`, `opening balance date [now - 2 weeks]`, `virtual balance 0`

8. Transfers
8.1. `Transfers` -> create new transaction from native (eur) to non-native (e.g. usd) account, with `date [now - 3 days]` (or later, so that this date is not today and is visible on the chart), amount `300 eur` -> `450 usd` for example. In fact the type of transaction does not matter, here it just allows to affect both accounts at once for demonstration

9. Enjoy!

### Note
`sudo -u www-data /usr/bin/php /var/www/<domain_name>/artisan correction:recalculate-native-amounts`
or
`sudo -u www-data /usr/bin/php /var/www/<domain_name>/artisan cache:clear`
or
`system settings` -> `clear cache`
affects only the correctness of values ​​and recalculations, as well as general graphs and graphs in reports, but does not affect the graph in the accounts with the native currency

**Comment by JC5** [comment]
Thanks for the excellent report! I'll verify later and check it out. 

But I must admit I'm surprised because this is exactly what I've been doing, and it seems to work.

**Comment by nebster9k** [comment]
Oh, it works :)

Initially I was going to make a similar issue, but I found this existing, in my case I initially noticed the problem not with the graphs inside the accounts, but with the general graph on the main page

And the fix really helped with it, now the problem remains only inside the accounts pages

I can assume that the mechanism for generating graphs is duplicated somewhere between the general graph and the account graphs, and the fix affected only the general one

**Comment by JC5** [comment]
I specifically tested all of them, but like I said, I will check it out!

**Comment by JC5** [comment]
Aha! Very nice. The account on the other side of a transfer. NOT tested, lol. Thanks!

**Comment by nebster9k** [comment]
Thanks for your work! It's nice to be part of improving a good product with great developer feedback

**Comment by JC5** [comment]
Hah, thanks. And you too, for the feedback you keep giving. Will you let me know if this works as expected? I haven't run a full regression test yet.

**Comment by nebster9k** [comment]
I did this first :), the test instance was still in the same state, I just applied the patch from d3b2748c8f387caf57c0d08b9417f2b05cd4132e to ee260a3df718177ca95ef5de04ef2495d866b498, and clear the cache, everything graphs (dashboard, accounts, reports) is displayed as it should, so on topic of the issue everything is fine. The rest of what I noticed concerns the calculation and display of non-native currencies in budgets, but issues for it is already exists
